PabloMK7/citra

src/core/core.cpp
src/core/hle/service/apt/applet_manager.cpp
src/core/hle/service/apt/ns.cpp
src/core/hle/service/apt/ns.h
src/core/hle/service/plgldr/plgldr.cpp
src/core/hle/service/plgldr/plgldr.h
src/core/loader/loader.h
src/core/loader/ncch.cpp

Implements the Luma3DS Mode3 plugin memory strategy, allowing plugins that rely in this mode to function properly.

Implement plugin loader Mode3 mem strategy

---

src/core/hle/kernel/svc.cpp

Adds two new types to svcGetSystemInfo so that homebrew applications can use them as they desire.

Add HOST_TICK and BUILD_PLATFORM to svcGetSystemInfo CITRA_INFORMATION type

---

src/android/app/src/main/jni/config.cpp
src/citra/config.cpp
src/citra_qt/configuration/config.cpp
src/citra_qt/configuration/configure_debug.cpp
src/citra_qt/configuration/configure_debug.ui
src/common/logging/backend.cpp
src/common/logging/backend.h
src/common/settings.h

Adds a configurable regex filter to the log, which allows displaying only those entries matching the regex.

Add regex filter to the log

---

src/audio_core/openal_sink.cpp
src/citra_qt/util/graphics_device_info.cpp
src/core/hle/service/soc/soc_u.cpp

Mostly to do with casting. Encountered them when I was trying to upgrade some of the submodules. Fixes #39.

Some build fixes for GCC 13.2.0 and Clang 18.1.1

---

src/core/file_sys/archive_extsavedata.cpp
src/core/file_sys/archive_sdmc.cpp
src/core/hle/kernel/svc.cpp
src/core/hle/service/fs/file.cpp
src/core/hle/service/fs/fs_user.cpp

Some FS functions were constantly throwing errors for missing files. Those are completely normal as it's just games checking if files exist by opening them, and were confusing some people, so the log level was reduced to Debug.
Stubbed some missing cache SVCs that are used commonly in homebrew apps and were throwing many errors.

Reduce log levels for some FS functions and stub cache svcs

---

src/core/hle/service/cam/y2r_u.cpp
src/core/hle/service/cam/y2r_u.h

The FIFA games have a bug in their code and rely on the Y2R decoding event not being signaled immediately. This PR adds the minimum delay I've found to fix the softlock and also implements IsBusyConversion.
Citra (PR) | Citra (master)
-|-

y2r: Delay completion event

---

src/video_core/rasterizer_cache/rasterizer_cache.h
src/video_core/rasterizer_cache/rasterizer_cache_base.h

Most 3DS game are relatively well behaved with their VRAM usage, with few framebuffers that don't overlap with each others. However since the system has UMA architecture, nothing stops games from using VRAM in weird ways. In some cases games will try to reuse VRAM by aliasing memory as entirely different textures. This isn't that terrible to handle if the stride stays the same, something that isn't always true.
Luigi's Mansion: Dark Moon will initially use a memory region as a framebuffer with 256 pixel stride, then reuse the same region as a framebuffer with 128 pixel stride. The contents are immediately cleared afterwards so the result doesn't really matter, but this trips up the texture cache and causes a useless and expensive gpu flush per frame.
Kid Icarus also does this. Through the …

rasterizer_cache: Improve validation skip heuristic

---

src/video_core/renderer_vulkan/vk_instance.cpp

This should resolve #66. I have not been able to test this on non macOS devices. This code was initially in CollectTelemetryParameters() but was removed in commit 0288877. I have re-added it to the CreateDevice function.

vk_instance.cpp: fix getting driver_id for vulkan device

---

src/core/file_sys/ncch_container.cpp

Adds support for loading IPS patches from the Luma3DS folders. This allows self-managed homebrew apps (such as Pretendo Network) that rely on Luma patches to work without having to move files manually.
Keep in mind that Pretendo's HTTP patches have a bug (https://github.com/PretendoNetwork/nimbus/issues/39) that causes the friend list to freeze. To fix the bug LLE HTTP has to be enabled and the HTTP patch has to be removed (using HLE HTTP also doesn't work because Pretendo's NASC server does not set the Content-Length header, which cause issues with the HLE implementation).

Allow loading IPS files from Luma3DS folders.

---

src/core/hle/kernel/resource_limit.cpp

The resource limit checks are being triggered for some unknown bug, which causes apps to crash sometimes. There is nothing wrong with ignoring the errors until all the bugs are fixed, to prevent crashes.

Remove resource limit checks for now.

---

src/citra_qt/debugger/console.cpp

If the console was already opened by the debugger, nothing would show up on it. We can check for ERROR_PERMISSION_DENIED and assume a console is already opened.

Fix showing color console if debugger attached on windows.

---

src/video_core/renderer_vulkan/renderer_vulkan.cpp

Fixes a few crashes if the image view is not populated correctly.

renderer_vulkan: Use proper image view on LCD fills

---

src/citra_qt/main.cpp
src/citra_qt/main.ui

I know there's multiple ways to access the Log folder (File Explorer, File->Open Citra Folder->Logs, the Debug interface, etc.) but people on the various forums and forks still keep asking how to access the logs or that they don't know where they are that perhaps a more obvious way to access them would be helpful. And being able to point people to `Help->Open Log Folder` may make the support burden easier as it's simpler to explain.

citra_qt: Add Open Log Folder option to Help menu

---

src/android/app/src/main/java/org/citra/citra_emu/fragments/HomeSettingsFragment.kt

When entering an address for an Artic Base server, the default value will be the address which was last entered
This is a feature which is already present on the desktop build, however it is currently absent in the mobile build

Android: Remember last entered Artic Base server address

---

src/common/static_lru_cache.h
src/core/file_sys/artic_cache.cpp

Fixes reads from cache when the read doesn't match the the expected read size. This fixes a link between worlds deleting its save file.

Artic Base: Fix out of bounds cache reads

---

src/core/file_sys/archive_artic.cpp

Removes the usage of the cache if the read would result in a read from OOB data. A more intelligent solution is possible, but this is a quick fix to prevent some games such as TLOZ: A Link Between Worlds to reset its save file.

Do not use the cache if the read would result in OOB

---

src/citra_qt/configuration/configure_system.ui

My laptop display is 1366x768 and the System tab takes up the majority of those 768 pixels to the point that the confirmation buttons are rendered off screen and because the tab is not resizable at that size, I have to switch to another tab that can be resized in order to access those buttons. So this PR adds a scroll bar to the System tab, which makes things a little easier for those with lower resolution displays.

citra_qt: Add scroll bar to System tab

---

src/citra_qt/main.cpp

The screenshot capture function is now working in the paused state, and using the feature will unpause the game and then capture the next frame to save as a screenshot.
A question prompt will first appear, before the game unpauses:

Run screenshot capture function in paused state by capturing next frame

---

src/core/hle/service/http/http_c.cpp
src/core/hle/service/http/http_c.h

Fixed the `RequestState` enum having the wrong valeus/meanings/documentation. Updated the HTTP HLE methods to use the values properly.
This change fixes Pretendo Network not working properly while using HLE HTTP. Using LLE HTTP is still broken due to a bug in Pretendo Network HTTP patch.

Fix HTTP RequestState values (fixes Pretendo Network support with HLE http)

---

src/citra_qt/configuration/configure_debug.ui
src/common/logging/formatter.h
src/core/hle/service/cfg/cfg.cpp
src/core/hle/service/ir/extra_hid.cpp
src/core/hle/service/ir/ir_user.cpp
src/core/hle/service/soc/soc_u.cpp
src/core/hle/service/soc/soc_u.h
src/core/movie.cpp
src/core/savestate.cpp
src/network/artic_base/artic_base_client.cpp
src/video_core/renderer_software/sw_clipper.cpp
src/video_core/renderer_vulkan/vk_instance.cpp
src/video_core/renderer_vulkan/vk_shader_util.cpp

Fix compilation errors, and update fmt for the same reason.
An example of a compilation error:
`error: comparison of integer expressions of different signedness: 'SocketHolder' {aka 'long long unsigned int'} and 'int' [-Werror=sign-compare]`
By updating fmt, it will fix:
`integer_sequence<bool, (Is == Is)...>  [-Werror=tautological-compare]`
The updating is helpful and needed.
Fmt has gone through two public versions since its last update and has fixed many bugs, including new compiler optimizations.
But neither of these two public versions can fix the errors encountered above.
We need to switch to a working version. Very helpful. The selected version works well.
Synchronously updating local code.
configure_debug.ui: there are two variables named repeatedly here, which raises a warning.

Fix gcc 13+ compilation and update fmt.

---

src/core/hle/service/cam/y2r_u.cpp

With the current code, is_busy_conversion would never be set to false if a game calls StopConversion mid-conversion. Which also means that IsBusyConversion would forever return true.

Y2R: Set is_busy_conversion to false when stopping conversion

---

src/tests/CMakeLists.txt
src/tests/video_core/shader.cpp
src/tests/video_core/shader/shader_jit_compiler.cpp

Uses Catch2's `TEMPLATE_TEST_CASE`-feature to test both the JIT and the interpreter.

shader_jit/tests: Test both the shader interpreter and jit

---

src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/IntSetting.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
src/android/app/src/main/jni/config.cpp
src/android/app/src/main/jni/default_ini.h
src/android/app/src/main/res/values-es/strings.xml
src/android/app/src/main/res/values/strings.xml
src/citra/config.cpp
src/citra_qt/configuration/config.cpp
src/citra_qt/configuration/configure_graphics.cpp
src/citra_qt/configuration/configure_graphics.ui
src/common/settings.cpp
src/common/settings.h
src/core/hle/service/gsp/gsp_gpu.cpp

Read this for more details: https://www.reddit.com/r/Citra/comments/1e1v4e1/fixing_luigis_mansion_2_performance_issues_once/
Adds a setting that puts the game render thread to sleep a certain amount of milliseconds. This helps with performance issues in dynamic-fps games, such as Luigi's Mansion 2.
UI changes:

Renderer: Implement setting to delay the game render thread

---

src/video_core/renderer_opengl/gl_driver.cpp
src/video_core/renderer_opengl/gl_driver.h
src/video_core/renderer_opengl/gl_rasterizer.cpp
src/video_core/renderer_opengl/gl_rasterizer.h

Reduces the texture buffer size in older Mali GPUs which have performance issues on buffers close to the max size.

Workaround a performance bug in older Mali GPUs

---

src/video_core/renderer_vulkan/renderer_vulkan.cpp
src/video_core/renderer_vulkan/vk_master_semaphore.cpp

Removes an unnecessary execution dependency on queue submissions and allows the gpu to process commands more in parallel.

renderer_vulkan: Reduce amount of wait semaphores

---

src/android/app/src/main/java/org/citra/citra_emu/NativeLibrary.kt
src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.kt
src/android/app/src/main/java/org/citra/citra_emu/features/hotkeys/Hotkey.kt
src/android/app/src/main/java/org/citra/citra_emu/features/hotkeys/HotkeyUtility.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/Settings.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/view/InputBindingSetting.kt
src/android/app/src/main/java/org/citra/citra_emu/fragments/EmulationFragment.kt
src/android/app/src/main/res/values/strings.xml
src/core/savestate.cpp
src/core/savestate.h

This adds a hotkey for quicksaving and quickloading. Each hotkey will show a toast after invoking.
They use a saveslot 11.
I also refactored the saves-popup-menu a bit.
Loading also closes the drawer now.
Saving&Loading from the drawer will also show a toast.
This PR was also opened in the Lime3DS repository. All code was written by me.

android: add quicksave hotkeys

---

src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/IntSetting.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
src/android/app/src/main/res/values/arrays.xml
src/android/app/src/main/res/values/strings.xml

This adds the ability to change the screen-orientation for the emulator in the settings. Live switching is possible.
This PR was also opened in the Lime3DS repository. All code was written by me.

android: implement device rotation options

---

src/android/app/src/main/java/org/citra/citra_emu/activities/EmulationActivity.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/view/InputBindingSetting.kt

See #184 
Closes #184
This implements the scancode fallback for unknown keys.
There is one drawback to this PR:
When a user already assigned an "unknown button" to an action, updating to this PR will render that button useless until it is remapped by the user. There is no indication that this happened, and it will fail silently.

android: Allow remapping of unknown keycodes

---

src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/IntSetting.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
src/android/app/src/main/jni/config.cpp
src/android/app/src/main/jni/default_ini.h
src/android/app/src/main/res/values-es/strings.xml
src/android/app/src/main/res/values/strings.xml
src/citra_qt/configuration/config.cpp
src/citra_qt/configuration/configure_dialog.cpp
src/citra_qt/configuration/configure_input.cpp
src/citra_qt/configuration/configure_input.h
src/citra_qt/configuration/configure_input.ui
src/common/settings.cpp
src/common/settings.h
src/core/hle/service/hid/hid.cpp
src/core/hle/service/hid/hid.h
src/core/hle/service/ir/extra_hid.cpp
src/core/hle/service/ir/extra_hid.h
src/core/hle/service/ir/ir_rst.cpp
src/core/hle/service/ir/ir_rst.h
src/core/hle/service/ir/ir_user.cpp
src/core/hle/service/ir/ir_user.h
src/core/loader/artic.cpp
src/network/artic_base/artic_base_client.cpp
src/network/artic_base/artic_base_client.h

Adds the ability to use the 3DS running the Artic Base Server as a controller.
The following works:
- Buttons
- Touch screen
- Accelerometer and gyroscope
- New 3DS specific buttons
The following doesn't work:
- Circle pad pro on the old 3ds (games that use it work if played through a new 3ds)
- Microphone and camera (no plans to add support)
The option is disabled by default and can be enabled from the controls tab in emulation settings.

Artic Base: Add Artic Controller support

---

src/core/file_sys/archive_artic.cpp
src/core/file_sys/artic_cache.cpp

Fixes an issue when a `FSFILE_Read` operation returns 0 bytes of data.
Closes #178

Artic Base: Fix issue when 0 bytes are read from file

---

src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/BooleanSetting.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
src/android/app/src/main/jni/config.cpp
src/android/app/src/main/jni/default_ini.h
src/android/app/src/main/res/values/strings.xml
src/citra/config.cpp
src/citra_qt/configuration/config.cpp
src/citra_qt/configuration/configure_debug.cpp
src/citra_qt/configuration/configure_debug.ui
src/common/logging/backend.cpp
src/common/settings.cpp
src/common/settings.h

Adds an option that immediately writes and flushes every single log message. Useful for better debugging some kinds of crashes as sometimes the log output gets cut.

Add instant log flush option

---

src/video_core/debug_utils/debug_utils.cpp

A mutex was being unnecessary locked on every GPU register write, even if the debug tracing feature was disabled. Fixed by moving the lock below the tracing enabled check.

pica: Move mutex lock below tracing check on register write

---

src/video_core/shader/shader_jit_a64_compiler.cpp
src/video_core/shader/shader_jit_a64_compiler.h

These conditional tests are a 1:1 translation from the x64 code but do not have to be. Reference-values are known at emit-time and can be embedded as an immediate into an `EOR` instruction rather than moved into a register. The `TST` instruction can be utilized to more optimally test and update the `EQ`/`NE` status flags.

shader_jit_a64: Optimize conditional tests

---

src/tests/video_core/shader.cpp
src/video_core/pica/shader_unit.cpp
src/video_core/pica/shader_unit.h
src/video_core/shader/shader_interpreter.cpp
src/video_core/shader/shader_jit_a64_compiler.cpp
src/video_core/shader/shader_jit_x64_compiler.cpp

Fix some of the regressions introduced by https://github.com/PabloMK7/citra/pull/229 and adds a further optimization that can be done at emit-time(COND{0,1} registers can be utilized immediately in the case that the inverted reference value is 0).
This also adds an exhaustive conditional code unit-test to better detect regressions on conditional code.
This also addresses an initialization issue in the Shader Interpreter.

shader_jit: Fix/optimize conditional evaluation

---

src/android/app/src/main/java/org/citra/citra_emu/adapters/GameAdapter.kt
src/android/app/src/main/res/layout/card_game.xml

Compared to game companies, users may be more interested in knowing what the title ID of this game is, 
as it can help them find game saves and the cheat file. 
In fact, many people have been troubled by not being able to find a game save location because they don't know what title ID is.
This PR will directly display the title ID in the game card, making it easier for users to find this ID. It replaced the game company.
old:
new:

Android: add the titleId to the game card.

---

src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/IntSetting.kt
src/android/app/src/main/jni/config.cpp
src/android/app/src/main/jni/default_ini.h
src/citra/config.cpp
src/citra/default_ini.h
src/citra_qt/configuration/config.cpp
src/citra_qt/configuration/configure_system.cpp
src/citra_qt/configuration/configure_system.ui
src/common/settings.h
src/core/hle/service/ptm/ptm.cpp

This implements a "Steps per hour" system setting to be returned from `PTM:GetStepHistory`, as described in issue #208.
Currently the setting is global (i.e. not per-game).

Add "Steps per hour" system setting

---

src/citra_qt/main.cpp

If there are multiple languages on a system, this fixes the annoying behavior of Citra not selecting the primary system language but the secondary one instead 
https://github.com/PabloMK7/citra/issues/74

qt: Fix default language not being set to the main one the system uses

---

src/android/app/src/main/jni/native.cpp

This fixes crashing if the game is paused on android
For me, Super Mario 3D Land was crashing as soon as I paused the game, but other people reported crashing after a couple paste/resume cycles anyway this should fix all pausing issues

android: Fix pause emulator button crashing the emulator

---

src/video_core/renderer_vulkan/vk_stream_buffer.cpp

This is a fix for GPUs with Vulkan V1.1 and V1.2.
This Fix is merged as of now in Lime3DS and tested working (commit #384 in Lime3DS)
Fixes Issue #233 in here.

Refactor Vulkan stream buffer memory type selection

---

src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/IntSetting.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
src/android/app/src/main/jni/default_ini.h
src/android/app/src/main/res/values/strings.xml
src/citra/default_ini.h
src/citra_qt/configuration/configure_system.ui

This should hopefully complete what was introduced in #211 .
Screenshots:

Android: Add Pedometer Steps per Hour settings UI

---

src/common/aarch64/oaknut_abi.h
src/common/aarch64/oaknut_util.h
src/video_core/shader/shader_jit_a64_compiler.cpp
src/video_core/shader/shader_jit_a64_compiler.h

Generates position-independent assembly to allow for code to be generated first within a `std::vector` before copying into executable memory. Allows for more compact memory-usage rather than allocating 1MiB of executable code for each shader. Saves up to ~1MiB for _each_ shader.

shader_jit_a64: Compact host executable memory

---

dist/citra.6

Simple update to make the `citra` man page match the options the executable can take. Not sure where to point the web links these days, so I didn't touch those.
It now looks like this:
```
citra(6)                                                                                                  Games Manual                                                                                                 citra(6)
NAME
Citra — Nintendo 3DS Emulator/Debugger (SDL)
SYNOPSIS
citra [options] [file]
OPTIONS
-g port, --gdbport port
Starts the GDB stub on the specified port
-i, --install FILE
Installs a specified CIA file
-m, --multiplayer nick:password@address:port
Nickname, password, address and port for multiplayer
-r, --movie-record file
Record a movie (game inputs) to the given file
-a, …
```

Update `citra(6)` man page

---

src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/BooleanSetting.kt

I'm sure this was an oversight by the original devs and not intended to actually be runtime editable guessing by Qt's behavior
See https://github.com/Lime3DS/Lime3DS/issues/442

android: Make `Asynchronous shader compilation` non runtime editable

---

src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/Settings.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/view/HeaderSetting.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/model/view/InputBindingSetting.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsActivity.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsFragmentPresenter.kt
src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/viewholder/HeaderViewHolder.kt
src/android/app/src/main/res/layout/list_item_settings_header.xml
src/android/app/src/main/res/values/strings.xml

Closes #255 by re-enabling the Dpad Axes as an option for controllers where the buttons aren't being detected. This code already existed in an earlier version of this, I'm just adding it back, but the new code is essentially identical to the code in Lime3DS so credit to those developers.
I am still looking into why the buttons don't work even when mapped in situations where an axis is also detected (Lime3DS has this issue as well), I will try to put in a hotfix for that eventually for maximum flexibility, but in the meantime this works.
There is a cleaner solution to this that I'd like to implement eventually, but this should at least make it functional for all.

Reenable dpad axes option

---

src/core/file_sys/plugin_3gx.cpp
src/core/file_sys/plugin_3gx.h
src/core/hle/kernel/svc.cpp
src/core/hle/service/plgldr/plgldr.cpp

Allows mapping memory regions with the PRIVATE state instead of the SHARED state.

Match changes to svcMapProcessMemoryEx from latest Luma3DS

---

src/core/hle/service/plgldr/plgldr.cpp

Fixes plugins incorrectly loading when applets are launched.

Make plugins only load for apps and not applets

---

src/citra_qt/dumping/option_set_dialog.cpp
src/common/dynamic_library/ffmpeg.cpp
src/common/dynamic_library/ffmpeg.h
src/core/dumping/ffmpeg_backend.cpp

After ffmpeg 5.1, it is deprecated, and has been completely removed in ffmpeg 7.
Our current project is using 6.0 headers, modifying it will not have any side effects.
For msys2, 
the version of ffmpeg has been updated to 7.0.2.
We may need to update the library headers.
https://github.com/PabloMK7/ext-library-headers/pull/1

FFmpeg: adapt to ffmpeg7 for dumping.
